### ISSUE TITLE
Plan to open-source

### ISSUE THREAD

**Issue by crhf** [NL2Code/CodeR#1]
Hi, thanks for the nice work! Do you have a plan to release the source code of CodeR, so that people can learn more about it?

**Comment by NL2Code** [comment]
Hi, thanks for your interest in our work. But unfortunately, we currently do not have plans to open source CodeR's code. Our code is based on the SWE-agent repo, updates AutoCodeRover's search actions, and adds some new actions.

If you have any questions during reproducting, please feel free to contact us.

**Comment by Randolph-zeng** [comment]
Hi, congratuations on the great work! However, since your paper used the source code from AutoCodeRover, it needs to be released under the same license GLP 3.0. Failure to comply with this license is a clear violation of the copyright law and does great damage to the reputation to all the stakeholders of the project.  Please kindly reconsider the open-source decision with the consequences it might leads to though.
